name: Deploy to Railway
on:
  push:
    branches:
      - ci-cd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECRET_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker image
        run: |
          docker-compose build
          docker-compose push
      - name: Deploy to Railway
        run: |
          railway deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
