name: Deploy to Railway
on:
  push:
    branches:
      - ci-cd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECRET_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker image
        run: |
          docker-compose build
          docker-compose push
      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli
      - name: Deploy to Railway
        run: |
          RAILWAY_TOKEN=$RAILWAY_TOKEN railway link
          railway up
          railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
          
          
